backend:
  name: github
  repo: solanto/garden # CHANGE ME
  branch: main
  base_url: https://cms.garden.solanto.me # CHANGE ME
  auth_endpoint: api/auth

media_folder: /assets
public_folder: /assets

collections:net
  - name: "notes"
    label: "notes"
    folder: "notes"
    create: true
    editor:
      preview: false
    fields:
      - { label: "slug", name: "slug", widget: "string" }
      - { label: "publish date", name: "date", widget: "datetime" }
      - { label: "icon", name: "icon", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }
