backend:
  name: github
  repo: solanto/garden
  branch: main
  base_url: https://cms.garden.solanto.me
  auth_endpoint: api/auth

media_folder: /assets
public_folder: /assets

collections:
  - name: "notes"
    label: "notes"
    folder: "notes"
    create: true
    nested:
      depth: 100
    editor:
      preview: true
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "publish date", name: "date", widget: "datetime" }
      - { label: "slug", name: "slug", widget: "string" }
      
